version: "3"

services:
  app_ex_1:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app_ex_1:/app_ex_1
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=postgres
      - DB_NAME=app_ex_1
      - DB_USER=postgres
      - DB_PASS=5048
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine3.16
    environment:
      - POSTGRES_DB=app_ex_1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5048
